services:
  nginx:
    build: 
      context: ./requirements/nginx/
    container_name: nginx
    ports: 
      - 443:443
    env_file:
     - .env
    depends_on:
      - wordpress
    networks:
     - inception
    volumes:
     - web:/var/www/wordpress
    restart: always
    secrets:
      - ssl_key
      - ssl_cert
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
     - .env
    environment:
      MARIADB_PASSWORD : /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD: /run/secrets/mariadb_root_password
    networks:
     - inception
    volumes:
      - data:/var/lib/mysql
    restart: always
    secrets:
      - mariadb_password
      - mariadb_root_password
  wordpress:
    build: ./requirements/wordpress/
    container_name : wordpress
    env_file:
     - .env
    environment:
      MARIADB_PASSWORD : /run/secrets/mariadb_password
      WP_ADMIN_PASS : /run/secrets/wp_admin_password
      WP_USER_PASS : /run/secrets/wp_user_password
    depends_on:
     - mariadb
    networks:
     - inception
    volumes:
      - web:/var/www/wordpress
    restart: always
    secrets:
      - mariadb_password
      - wp_admin_password
      - wp_user_password
networks:
  inception:
    driver: bridge
volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: /Users/borito/inception/data/web/
      o : bind
  data:
    driver: local
    driver_opts:
      type: none
      device: /Users/borito/inception/data/mariadb/
      o : bind
secrets:
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  mariadb_password:
    file: ../secrets/mariadb_password.txt
  mariadb_root_password:
    file: ../secrets/mariadb_root_password.txt
  ssl_key:
    file: ../secrets/bverdeci.42.fr.key
  ssl_cert:
    file: ../secrets/bverdeci.42.fr.crt
